---
- file:
    state: link
    src: "{{cops_sentry_d}}"
    path: "{{cops_sentry_c}}"
- include_role: {name: corpusops.roles/configs}
  vars:
    cops_configs_templates: "{{cops_sentry_configs_templates}}"
    cops_configs_prefix: "{{cops_sentry_configs_prefix}}"
- shell: |-
    set -ex
    cd "{{cops_sentry_d}}"
    sed -i -re "/^COMPOSE_PROJECT_NAME=/d" .env
- blockinfile:
    content: "{{cops_sentry_docker_env}}"
    marker: "# {mark} ANSIBLE extra conf"
    path: "{{cops_sentry_d}}/.env"
- name: compose pull
  shell: |-
    set -e
    cd "{{cops_sentry_d}}"
    {{cops_sentry_dc}} pull
  tags: [sentry_pull]
- name: compose build
  shell: |-
    set +e
    cd "{{cops_sentry_d}}"
    {{cops_sentry_dc}} build
    echo "dcret:$?"
  register: composebuild
  retries: 2
  delay: 0
  until: "'dcret:0' in composebuild.stdout"
  tags: [sentry_build]
