---
- block:
  - include_tasks: checkout.yml
  tags: ["cops_sentry_checkout"]
  when: ["cops_sentry_checkout|default(true)"]
- block:
  - include_tasks: configure.yml
  tags: ["cops_sentry_configure"]
  when: ["cops_sentry_configure|default(true)"]
- block:
  - include_tasks: services.yml
  tags: ["cops_sentry_services"]
  when: ["cops_sentry_services|default(true)"]
- block:
  - include_tasks: content.yml
  tags: ["cops_sentry_content"]
  when: ["cops_sentry_content|default(true)"]
