---
version: '3.4'
x-env-defaults: &img_defaults
  redis: &env_redis
    REDIS_PASSWORD: "{{cops_sentry_redis_password}}"
  postgres: &env_postgres
    POSTGRESQL_PASSWORD: "{{cops_sentry_db_password}}"
    POSTGRESQL_DB: "{{cops_sentry_db_name}}"
    POSTGRESQL_USER: "{{cops_sentry_db_user}}"
    PGDATA: /var/lib/postgresql/data/pgdata
  sentry: &env_sentry
    <<: [ *env_postgres, *env_redis]
    SENTRY_DATADIR: "{{cops_sentry_data}}"
    SENTRY_SECRET_KEY: "{{cops_sentry_secret_key}}"
    SENTRY_BROKER_URL: "redis://:{{cops_sentry_redis_password}}@redis:6379/0"
    SENTRY_MEMCACHED_HOST: "memcached"
    SENTRY_SERVER_EMAIL: "{{cops_sentry_email_from}}"
    SENTRY_EMAIL_HOST: "smtp"
    SENTRY_EMAIL_PORT: "25"
    SENTRY_EMAIL_USER: "{{cops_sentry_email_local_relay_user}}"
    SENTRY_EMAIL_PASSWORD: "{{cops_sentry_email_local_relay_password}}"
    SENTRY_SINGLE_ORGANIZATION: "False"
  smtp: &env_smtp
    RELAY_POSTMASTER: "postmaster@{{cops_sentry_email_relay_domain}}"
    RELAY_MYHOSTNAME: "{{cops_sentry_email_relay_domain}}"
    RELAY_MYDOMAIN: "{{cops_sentry_email_relay_domain}}"
    RELAY_MYNETWORKS: "127.0.0.0/8"
    RELAY_HOST: "[{{cops_sentry_email_server}}]:{{cops_sentry_email_server_port}}"
    RELAY_MODE: "ALLOW_AUTH_NODOMAIN"
    RELAY_STRICT_SENDER_MYDOMAIN: "false"
    RELAY_LOGIN: "{{cops_sentry_email_username}}"
    RELAY_PASSWORD: "{{cops_sentry_email_password}}"
    RELAY_USE_TLS: "no"
    RELAY_EXTRAS_SETTINGS: "compatibility_level=1"
x-defaults: &defaults
  environment: { <<:  *env_sentry }
  volumes:
  - "{{cops_sentry_data_files}}:/var/lib/sentry/files"
services:
  web:
    <<: [ *defaults ]
    ports:
    - '127.0.0.1:{{cops_sentry_port}}:9000'
  worker:
    environment: { <<: *env_sentry }
  cron:
    environment: { <<: *env_sentry }
  backup:
    environment: { <<: *env_postgres }
    image: corpusops/dbsmartbackup
    restart: unless-stopped
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
    - ./local/backup/setup/reconfigure.yml:/setup/reconfigure.yml:ro
    - "{{cops_sentry_data_backup}}:/srv/backups"
  postgres:
    environment: { <<: *env_postgres }
    volumes:
    - "{{cops_sentry_data_postgresql}}:/var/lib/postgresql/data"
  redis:
    environment: { <<: *env_redis }
    cap_add:
    - sys_resource
  memcached:
    environment: { <<: *env_sentry }
  smtp:
    image: "turgon37/smtp-relay"
    environment: { <<: *env_smtp }
    volumes:
    - "{{cops_sentry_data_mail}}:/data"
